services:
  - type: worker
    name: telegram-bot
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: GOOGLE_SHEET_NAME
        sync: false
      - key: GOOGLE_CREDS_JSON
        sync: false
    dockerfilePath: Dockerfile
